### ISSUE TITLE
Broken elements of backend when using magento2-upward-connector with Venia

### ISSUE THREAD

**Issue by cat-nq** [magento/magento2-upward-connector#23] opened 2020-01-16 06:39 UTC
Hi,

When I turn on the magento2-upward-connector module, the front-end works well with Venia and Magento 2.3.3 but there are a lot of issues in the Magento backend: 
- impossible to load orders, products, categories, customers, CMS pages, blocks, etc.
- bug when switching to another store view (for example in Store > Configuration)

I redeployed the static files for the admin area to be sure this wasn't the issue, but I still have the same problems. I tried reindexing, flushing the cache, etc.
I tried with the latest release and version dev-develop: same issues.  

Can someone fix that or give me a solution please? 

Thank you,
Catherine

**Comment by tjwiebell** [comment] 2020-01-16 15:22
@cat-nq - We're tracking an issue internally related to shared hostnames between the frontend and the backend, which results in the ServiceWorker trying to handle request for admin area requests that it shouldn't be, and causing some unexpected behavior like you're seeing. A simple work around is to do backend tasks in a private browser session.

I'll be sure to link this issue to our internal bug, and will update you when a patch is available.

**Comment by dmytro-ch** [comment] 2020-02-28 13:39
I guess, as a temporary solution, the issue can be solved by unregistering the service worker for backend pages, or even for all standard storefront pages. Because the same issue may appear if we use the "Front Name Whitelist" configuration in order to exclude some frontend pages.

**Comment by tjwiebell** [comment] 2021-09-29 14:22
This was patched in https://github.com/magento-commerce/magento2-upward-connector/pull/1, and we've added guidance to the [README](https://github.com/magento/magento2-upward-connector#service-worker-note) about multi-tab support if your storefront and backend share the same hostname.

Closing as resolved.

**Closed by tjwiebell** 2021-09-29 14:22 UTC
